# Generated by Django 2.2.17 on 2021-03-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regore', '0002_ore_collaboratore'),
    ]

    operations = [
        migrations.AddField(
            model_name='progetto',
            name='archivio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
