# Generated by Django 2.2.17 on 2021-03-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regore', '0003_progetto_archivio'),
    ]

    operations = [
        migrations.AddField(
            model_name='progetto',
            name='privato',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
