# Generated by Django 2.2.17 on 2021-04-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regore', '0004_progetto_privato'),
    ]

    operations = [
        migrations.AddField(
            model_name='progetto',
            name='protocollo',
            field=models.CharField(blank=True, default=0, max_length=6, null=True),
        ),
    ]
