# Generated by Django 2.2.17 on 2021-04-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regore', '0006_diario0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario0',
            name='data',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='diario0',
            name='tipo',
            field=models.CharField(blank=True, choices=[('in', 'consegna/ricezione'), ('tr', 'incontro/colloquio/avviso/email/posta'), ('nb', 'sviluppo/nota/promemoria'), ('td', 'todo/da fare')], max_length=100),
        ),
    ]
