# Generated by Django 2.2.17 on 2021-01-11 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboratore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('cognome', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Collaboratore',
            },
        ),
        migrations.CreateModel(
            name='Progetto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.DateField(verbose_name='%Y')),
                ('nome', models.CharField(max_length=200)),
                ('luogo', models.CharField(max_length=100)),
                ('protocollo', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name_plural': 'Progetti',
            },
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('testo', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodiario.Collaboratore')),
                ('progetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodiario.Progetto')),
            ],
            options={
                'verbose_name_plural': 'Diario',
            },
        ),
    ]
