# Generated by Django 2.2.17 on 2021-01-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodiario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='testo',
            field=models.TextField(),
        ),
    ]
