# Generated by Django 2.2.17 on 2021-02-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodiario', '0002_auto_20210111_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='diario',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='diario',
            name='tipo',
            field=models.CharField(choices=[('co', 'consegna'), ('em', 'email'), ('in', 'incontro'), ('sv', 'sviluppo'), ('ev', 'evento'), ('no', 'nota')], max_length=100),
        ),
    ]
