# Generated by Django 2.2.17 on 2021-03-22 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodiario', '0003_auto_20210221_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
