# Generated by Django 2.2.17 on 2021-03-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodiario', '0004_auto_20210322_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
