# Generated by Django 2.2.17 on 2021-03-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodiario', '0006_auto_20210329_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='progetto',
            name='archivio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='progetto',
            name='privato',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
