# Generated by Django 2.2.17 on 2021-04-05 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodiario', '0007_auto_20210329_1807'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collaboratore',
        ),
    ]
