# Generated by Django 2.2.17 on 2021-04-05 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regore', '0005_progetto_protocollo'),
        ('prodiario', '0008_delete_collaboratore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Progetto',
            new_name='Progetto_00',
        ),
        migrations.RenameField(
            model_name='diario',
            old_name='progetto',
            new_name='progetto_00',
        ),
        migrations.AddField(
            model_name='diario',
            name='progetto_01',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regore.Progetto'),
        ),
    ]
