# Generated by Django 2.2.17 on 2021-04-05 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodiario', '0009_auto_20210405_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='progetto_00',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prodiario.Progetto_00'),
        ),
    ]
